# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.18.4/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR/CMakeFiles /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named CityTrafficSimulator

# Build rule for target.
CityTrafficSimulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CityTrafficSimulator
.PHONY : CityTrafficSimulator

# fast build rule for target.
CityTrafficSimulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/build
.PHONY : CityTrafficSimulator/fast

Code/AssetManager.o: Code/AssetManager.cpp.o

.PHONY : Code/AssetManager.o

# target to build an object file
Code/AssetManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/AssetManager.cpp.o
.PHONY : Code/AssetManager.cpp.o

Code/AssetManager.i: Code/AssetManager.cpp.i

.PHONY : Code/AssetManager.i

# target to preprocess a source file
Code/AssetManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/AssetManager.cpp.i
.PHONY : Code/AssetManager.cpp.i

Code/AssetManager.s: Code/AssetManager.cpp.s

.PHONY : Code/AssetManager.s

# target to generate assembly for a file
Code/AssetManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/AssetManager.cpp.s
.PHONY : Code/AssetManager.cpp.s

Code/Button.o: Code/Button.cpp.o

.PHONY : Code/Button.o

# target to build an object file
Code/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Button.cpp.o
.PHONY : Code/Button.cpp.o

Code/Button.i: Code/Button.cpp.i

.PHONY : Code/Button.i

# target to preprocess a source file
Code/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Button.cpp.i
.PHONY : Code/Button.cpp.i

Code/Button.s: Code/Button.cpp.s

.PHONY : Code/Button.s

# target to generate assembly for a file
Code/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Button.cpp.s
.PHONY : Code/Button.cpp.s

Code/CamerasView.o: Code/CamerasView.cpp.o

.PHONY : Code/CamerasView.o

# target to build an object file
Code/CamerasView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CamerasView.cpp.o
.PHONY : Code/CamerasView.cpp.o

Code/CamerasView.i: Code/CamerasView.cpp.i

.PHONY : Code/CamerasView.i

# target to preprocess a source file
Code/CamerasView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CamerasView.cpp.i
.PHONY : Code/CamerasView.cpp.i

Code/CamerasView.s: Code/CamerasView.cpp.s

.PHONY : Code/CamerasView.s

# target to generate assembly for a file
Code/CamerasView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CamerasView.cpp.s
.PHONY : Code/CamerasView.cpp.s

Code/Cell.o: Code/Cell.cpp.o

.PHONY : Code/Cell.o

# target to build an object file
Code/Cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Cell.cpp.o
.PHONY : Code/Cell.cpp.o

Code/Cell.i: Code/Cell.cpp.i

.PHONY : Code/Cell.i

# target to preprocess a source file
Code/Cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Cell.cpp.i
.PHONY : Code/Cell.cpp.i

Code/Cell.s: Code/Cell.cpp.s

.PHONY : Code/Cell.s

# target to generate assembly for a file
Code/Cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Cell.cpp.s
.PHONY : Code/Cell.cpp.s

Code/CreatorHandler.o: Code/CreatorHandler.cpp.o

.PHONY : Code/CreatorHandler.o

# target to build an object file
Code/CreatorHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorHandler.cpp.o
.PHONY : Code/CreatorHandler.cpp.o

Code/CreatorHandler.i: Code/CreatorHandler.cpp.i

.PHONY : Code/CreatorHandler.i

# target to preprocess a source file
Code/CreatorHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorHandler.cpp.i
.PHONY : Code/CreatorHandler.cpp.i

Code/CreatorHandler.s: Code/CreatorHandler.cpp.s

.PHONY : Code/CreatorHandler.s

# target to generate assembly for a file
Code/CreatorHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorHandler.cpp.s
.PHONY : Code/CreatorHandler.cpp.s

Code/CreatorState.o: Code/CreatorState.cpp.o

.PHONY : Code/CreatorState.o

# target to build an object file
Code/CreatorState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorState.cpp.o
.PHONY : Code/CreatorState.cpp.o

Code/CreatorState.i: Code/CreatorState.cpp.i

.PHONY : Code/CreatorState.i

# target to preprocess a source file
Code/CreatorState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorState.cpp.i
.PHONY : Code/CreatorState.cpp.i

Code/CreatorState.s: Code/CreatorState.cpp.s

.PHONY : Code/CreatorState.s

# target to generate assembly for a file
Code/CreatorState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorState.cpp.s
.PHONY : Code/CreatorState.cpp.s

Code/CreatorSubject.o: Code/CreatorSubject.cpp.o

.PHONY : Code/CreatorSubject.o

# target to build an object file
Code/CreatorSubject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorSubject.cpp.o
.PHONY : Code/CreatorSubject.cpp.o

Code/CreatorSubject.i: Code/CreatorSubject.cpp.i

.PHONY : Code/CreatorSubject.i

# target to preprocess a source file
Code/CreatorSubject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorSubject.cpp.i
.PHONY : Code/CreatorSubject.cpp.i

Code/CreatorSubject.s: Code/CreatorSubject.cpp.s

.PHONY : Code/CreatorSubject.s

# target to generate assembly for a file
Code/CreatorSubject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorSubject.cpp.s
.PHONY : Code/CreatorSubject.cpp.s

Code/Grid.o: Code/Grid.cpp.o

.PHONY : Code/Grid.o

# target to build an object file
Code/Grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Grid.cpp.o
.PHONY : Code/Grid.cpp.o

Code/Grid.i: Code/Grid.cpp.i

.PHONY : Code/Grid.i

# target to preprocess a source file
Code/Grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Grid.cpp.i
.PHONY : Code/Grid.cpp.i

Code/Grid.s: Code/Grid.cpp.s

.PHONY : Code/Grid.s

# target to generate assembly for a file
Code/Grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Grid.cpp.s
.PHONY : Code/Grid.cpp.s

Code/InitCreateState.o: Code/InitCreateState.cpp.o

.PHONY : Code/InitCreateState.o

# target to build an object file
Code/InitCreateState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/InitCreateState.cpp.o
.PHONY : Code/InitCreateState.cpp.o

Code/InitCreateState.i: Code/InitCreateState.cpp.i

.PHONY : Code/InitCreateState.i

# target to preprocess a source file
Code/InitCreateState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/InitCreateState.cpp.i
.PHONY : Code/InitCreateState.cpp.i

Code/InitCreateState.s: Code/InitCreateState.cpp.s

.PHONY : Code/InitCreateState.s

# target to generate assembly for a file
Code/InitCreateState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/InitCreateState.cpp.s
.PHONY : Code/InitCreateState.cpp.s

Code/InputManager.o: Code/InputManager.cpp.o

.PHONY : Code/InputManager.o

# target to build an object file
Code/InputManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/InputManager.cpp.o
.PHONY : Code/InputManager.cpp.o

Code/InputManager.i: Code/InputManager.cpp.i

.PHONY : Code/InputManager.i

# target to preprocess a source file
Code/InputManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/InputManager.cpp.i
.PHONY : Code/InputManager.cpp.i

Code/InputManager.s: Code/InputManager.cpp.s

.PHONY : Code/InputManager.s

# target to generate assembly for a file
Code/InputManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/InputManager.cpp.s
.PHONY : Code/InputManager.cpp.s

Code/MainMenuState.o: Code/MainMenuState.cpp.o

.PHONY : Code/MainMenuState.o

# target to build an object file
Code/MainMenuState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/MainMenuState.cpp.o
.PHONY : Code/MainMenuState.cpp.o

Code/MainMenuState.i: Code/MainMenuState.cpp.i

.PHONY : Code/MainMenuState.i

# target to preprocess a source file
Code/MainMenuState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/MainMenuState.cpp.i
.PHONY : Code/MainMenuState.cpp.i

Code/MainMenuState.s: Code/MainMenuState.cpp.s

.PHONY : Code/MainMenuState.s

# target to generate assembly for a file
Code/MainMenuState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/MainMenuState.cpp.s
.PHONY : Code/MainMenuState.cpp.s

Code/MapView.o: Code/MapView.cpp.o

.PHONY : Code/MapView.o

# target to build an object file
Code/MapView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/MapView.cpp.o
.PHONY : Code/MapView.cpp.o

Code/MapView.i: Code/MapView.cpp.i

.PHONY : Code/MapView.i

# target to preprocess a source file
Code/MapView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/MapView.cpp.i
.PHONY : Code/MapView.cpp.i

Code/MapView.s: Code/MapView.cpp.s

.PHONY : Code/MapView.s

# target to generate assembly for a file
Code/MapView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/MapView.cpp.s
.PHONY : Code/MapView.cpp.s

Code/Road.o: Code/Road.cpp.o

.PHONY : Code/Road.o

# target to build an object file
Code/Road.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Road.cpp.o
.PHONY : Code/Road.cpp.o

Code/Road.i: Code/Road.cpp.i

.PHONY : Code/Road.i

# target to preprocess a source file
Code/Road.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Road.cpp.i
.PHONY : Code/Road.cpp.i

Code/Road.s: Code/Road.cpp.s

.PHONY : Code/Road.s

# target to generate assembly for a file
Code/Road.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Road.cpp.s
.PHONY : Code/Road.cpp.s

Code/Simulator.o: Code/Simulator.cpp.o

.PHONY : Code/Simulator.o

# target to build an object file
Code/Simulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Simulator.cpp.o
.PHONY : Code/Simulator.cpp.o

Code/Simulator.i: Code/Simulator.cpp.i

.PHONY : Code/Simulator.i

# target to preprocess a source file
Code/Simulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Simulator.cpp.i
.PHONY : Code/Simulator.cpp.i

Code/Simulator.s: Code/Simulator.cpp.s

.PHONY : Code/Simulator.s

# target to generate assembly for a file
Code/Simulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Simulator.cpp.s
.PHONY : Code/Simulator.cpp.s

Code/SplashState.o: Code/SplashState.cpp.o

.PHONY : Code/SplashState.o

# target to build an object file
Code/SplashState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SplashState.cpp.o
.PHONY : Code/SplashState.cpp.o

Code/SplashState.i: Code/SplashState.cpp.i

.PHONY : Code/SplashState.i

# target to preprocess a source file
Code/SplashState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SplashState.cpp.i
.PHONY : Code/SplashState.cpp.i

Code/SplashState.s: Code/SplashState.cpp.s

.PHONY : Code/SplashState.s

# target to generate assembly for a file
Code/SplashState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SplashState.cpp.s
.PHONY : Code/SplashState.cpp.s

Code/StateMachine.o: Code/StateMachine.cpp.o

.PHONY : Code/StateMachine.o

# target to build an object file
Code/StateMachine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/StateMachine.cpp.o
.PHONY : Code/StateMachine.cpp.o

Code/StateMachine.i: Code/StateMachine.cpp.i

.PHONY : Code/StateMachine.i

# target to preprocess a source file
Code/StateMachine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/StateMachine.cpp.i
.PHONY : Code/StateMachine.cpp.i

Code/StateMachine.s: Code/StateMachine.cpp.s

.PHONY : Code/StateMachine.s

# target to generate assembly for a file
Code/StateMachine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/StateMachine.cpp.s
.PHONY : Code/StateMachine.cpp.s

Code/Tests/Tests.o: Code/Tests/Tests.cpp.o

.PHONY : Code/Tests/Tests.o

# target to build an object file
Code/Tests/Tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/Tests.cpp.o
.PHONY : Code/Tests/Tests.cpp.o

Code/Tests/Tests.i: Code/Tests/Tests.cpp.i

.PHONY : Code/Tests/Tests.i

# target to preprocess a source file
Code/Tests/Tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/Tests.cpp.i
.PHONY : Code/Tests/Tests.cpp.i

Code/Tests/Tests.s: Code/Tests/Tests.cpp.s

.PHONY : Code/Tests/Tests.s

# target to generate assembly for a file
Code/Tests/Tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/Tests.cpp.s
.PHONY : Code/Tests/Tests.cpp.s

Code/Tests/catch_amalgamated.o: Code/Tests/catch_amalgamated.cpp.o

.PHONY : Code/Tests/catch_amalgamated.o

# target to build an object file
Code/Tests/catch_amalgamated.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/catch_amalgamated.cpp.o
.PHONY : Code/Tests/catch_amalgamated.cpp.o

Code/Tests/catch_amalgamated.i: Code/Tests/catch_amalgamated.cpp.i

.PHONY : Code/Tests/catch_amalgamated.i

# target to preprocess a source file
Code/Tests/catch_amalgamated.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/catch_amalgamated.cpp.i
.PHONY : Code/Tests/catch_amalgamated.cpp.i

Code/Tests/catch_amalgamated.s: Code/Tests/catch_amalgamated.cpp.s

.PHONY : Code/Tests/catch_amalgamated.s

# target to generate assembly for a file
Code/Tests/catch_amalgamated.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/catch_amalgamated.cpp.s
.PHONY : Code/Tests/catch_amalgamated.cpp.s

Code/ToolsView.o: Code/ToolsView.cpp.o

.PHONY : Code/ToolsView.o

# target to build an object file
Code/ToolsView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/ToolsView.cpp.o
.PHONY : Code/ToolsView.cpp.o

Code/ToolsView.i: Code/ToolsView.cpp.i

.PHONY : Code/ToolsView.i

# target to preprocess a source file
Code/ToolsView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/ToolsView.cpp.i
.PHONY : Code/ToolsView.cpp.i

Code/ToolsView.s: Code/ToolsView.cpp.s

.PHONY : Code/ToolsView.s

# target to generate assembly for a file
Code/ToolsView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/ToolsView.cpp.s
.PHONY : Code/ToolsView.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... CityTrafficSimulator"
	@echo "... Code/AssetManager.o"
	@echo "... Code/AssetManager.i"
	@echo "... Code/AssetManager.s"
	@echo "... Code/Button.o"
	@echo "... Code/Button.i"
	@echo "... Code/Button.s"
	@echo "... Code/CamerasView.o"
	@echo "... Code/CamerasView.i"
	@echo "... Code/CamerasView.s"
	@echo "... Code/Cell.o"
	@echo "... Code/Cell.i"
	@echo "... Code/Cell.s"
	@echo "... Code/CreatorHandler.o"
	@echo "... Code/CreatorHandler.i"
	@echo "... Code/CreatorHandler.s"
	@echo "... Code/CreatorState.o"
	@echo "... Code/CreatorState.i"
	@echo "... Code/CreatorState.s"
	@echo "... Code/CreatorSubject.o"
	@echo "... Code/CreatorSubject.i"
	@echo "... Code/CreatorSubject.s"
	@echo "... Code/Grid.o"
	@echo "... Code/Grid.i"
	@echo "... Code/Grid.s"
	@echo "... Code/InitCreateState.o"
	@echo "... Code/InitCreateState.i"
	@echo "... Code/InitCreateState.s"
	@echo "... Code/InputManager.o"
	@echo "... Code/InputManager.i"
	@echo "... Code/InputManager.s"
	@echo "... Code/MainMenuState.o"
	@echo "... Code/MainMenuState.i"
	@echo "... Code/MainMenuState.s"
	@echo "... Code/MapView.o"
	@echo "... Code/MapView.i"
	@echo "... Code/MapView.s"
	@echo "... Code/Road.o"
	@echo "... Code/Road.i"
	@echo "... Code/Road.s"
	@echo "... Code/Simulator.o"
	@echo "... Code/Simulator.i"
	@echo "... Code/Simulator.s"
	@echo "... Code/SplashState.o"
	@echo "... Code/SplashState.i"
	@echo "... Code/SplashState.s"
	@echo "... Code/StateMachine.o"
	@echo "... Code/StateMachine.i"
	@echo "... Code/StateMachine.s"
	@echo "... Code/Tests/Tests.o"
	@echo "... Code/Tests/Tests.i"
	@echo "... Code/Tests/Tests.s"
	@echo "... Code/Tests/catch_amalgamated.o"
	@echo "... Code/Tests/catch_amalgamated.i"
	@echo "... Code/Tests/catch_amalgamated.s"
	@echo "... Code/ToolsView.o"
	@echo "... Code/ToolsView.i"
	@echo "... Code/ToolsView.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

