# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR/CMakeFiles /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CityTrafficSimulator

# Build rule for target.
CityTrafficSimulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CityTrafficSimulator
.PHONY : CityTrafficSimulator

# fast build rule for target.
CityTrafficSimulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/build
.PHONY : CityTrafficSimulator/fast

Code/Tests/BoostTest/converter_test.o: Code/Tests/BoostTest/converter_test.cpp.o

.PHONY : Code/Tests/BoostTest/converter_test.o

# target to build an object file
Code/Tests/BoostTest/converter_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/converter_test.cpp.o
.PHONY : Code/Tests/BoostTest/converter_test.cpp.o

Code/Tests/BoostTest/converter_test.i: Code/Tests/BoostTest/converter_test.cpp.i

.PHONY : Code/Tests/BoostTest/converter_test.i

# target to preprocess a source file
Code/Tests/BoostTest/converter_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/converter_test.cpp.i
.PHONY : Code/Tests/BoostTest/converter_test.cpp.i

Code/Tests/BoostTest/converter_test.s: Code/Tests/BoostTest/converter_test.cpp.s

.PHONY : Code/Tests/BoostTest/converter_test.s

# target to generate assembly for a file
Code/Tests/BoostTest/converter_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/converter_test.cpp.s
.PHONY : Code/Tests/BoostTest/converter_test.cpp.s

Code/Tests/BoostTest/file_finder_test.o: Code/Tests/BoostTest/file_finder_test.cpp.o

.PHONY : Code/Tests/BoostTest/file_finder_test.o

# target to build an object file
Code/Tests/BoostTest/file_finder_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/file_finder_test.cpp.o
.PHONY : Code/Tests/BoostTest/file_finder_test.cpp.o

Code/Tests/BoostTest/file_finder_test.i: Code/Tests/BoostTest/file_finder_test.cpp.i

.PHONY : Code/Tests/BoostTest/file_finder_test.i

# target to preprocess a source file
Code/Tests/BoostTest/file_finder_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/file_finder_test.cpp.i
.PHONY : Code/Tests/BoostTest/file_finder_test.cpp.i

Code/Tests/BoostTest/file_finder_test.s: Code/Tests/BoostTest/file_finder_test.cpp.s

.PHONY : Code/Tests/BoostTest/file_finder_test.s

# target to generate assembly for a file
Code/Tests/BoostTest/file_finder_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/file_finder_test.cpp.s
.PHONY : Code/Tests/BoostTest/file_finder_test.cpp.s

Code/Tests/BoostTest/init_create_state_helper_test.o: Code/Tests/BoostTest/init_create_state_helper_test.cpp.o

.PHONY : Code/Tests/BoostTest/init_create_state_helper_test.o

# target to build an object file
Code/Tests/BoostTest/init_create_state_helper_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/init_create_state_helper_test.cpp.o
.PHONY : Code/Tests/BoostTest/init_create_state_helper_test.cpp.o

Code/Tests/BoostTest/init_create_state_helper_test.i: Code/Tests/BoostTest/init_create_state_helper_test.cpp.i

.PHONY : Code/Tests/BoostTest/init_create_state_helper_test.i

# target to preprocess a source file
Code/Tests/BoostTest/init_create_state_helper_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/init_create_state_helper_test.cpp.i
.PHONY : Code/Tests/BoostTest/init_create_state_helper_test.cpp.i

Code/Tests/BoostTest/init_create_state_helper_test.s: Code/Tests/BoostTest/init_create_state_helper_test.cpp.s

.PHONY : Code/Tests/BoostTest/init_create_state_helper_test.s

# target to generate assembly for a file
Code/Tests/BoostTest/init_create_state_helper_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/init_create_state_helper_test.cpp.s
.PHONY : Code/Tests/BoostTest/init_create_state_helper_test.cpp.s

Code/Tests/BoostTest/main_menu_state_test.o: Code/Tests/BoostTest/main_menu_state_test.cpp.o

.PHONY : Code/Tests/BoostTest/main_menu_state_test.o

# target to build an object file
Code/Tests/BoostTest/main_menu_state_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/main_menu_state_test.cpp.o
.PHONY : Code/Tests/BoostTest/main_menu_state_test.cpp.o

Code/Tests/BoostTest/main_menu_state_test.i: Code/Tests/BoostTest/main_menu_state_test.cpp.i

.PHONY : Code/Tests/BoostTest/main_menu_state_test.i

# target to preprocess a source file
Code/Tests/BoostTest/main_menu_state_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/main_menu_state_test.cpp.i
.PHONY : Code/Tests/BoostTest/main_menu_state_test.cpp.i

Code/Tests/BoostTest/main_menu_state_test.s: Code/Tests/BoostTest/main_menu_state_test.cpp.s

.PHONY : Code/Tests/BoostTest/main_menu_state_test.s

# target to generate assembly for a file
Code/Tests/BoostTest/main_menu_state_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/main_menu_state_test.cpp.s
.PHONY : Code/Tests/BoostTest/main_menu_state_test.cpp.s

Code/Tests/BoostTest/map_view_test.o: Code/Tests/BoostTest/map_view_test.cpp.o

.PHONY : Code/Tests/BoostTest/map_view_test.o

# target to build an object file
Code/Tests/BoostTest/map_view_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/map_view_test.cpp.o
.PHONY : Code/Tests/BoostTest/map_view_test.cpp.o

Code/Tests/BoostTest/map_view_test.i: Code/Tests/BoostTest/map_view_test.cpp.i

.PHONY : Code/Tests/BoostTest/map_view_test.i

# target to preprocess a source file
Code/Tests/BoostTest/map_view_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/map_view_test.cpp.i
.PHONY : Code/Tests/BoostTest/map_view_test.cpp.i

Code/Tests/BoostTest/map_view_test.s: Code/Tests/BoostTest/map_view_test.cpp.s

.PHONY : Code/Tests/BoostTest/map_view_test.s

# target to generate assembly for a file
Code/Tests/BoostTest/map_view_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/map_view_test.cpp.s
.PHONY : Code/Tests/BoostTest/map_view_test.cpp.s

Code/Tests/BoostTest/vehicle_test.o: Code/Tests/BoostTest/vehicle_test.cpp.o

.PHONY : Code/Tests/BoostTest/vehicle_test.o

# target to build an object file
Code/Tests/BoostTest/vehicle_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/vehicle_test.cpp.o
.PHONY : Code/Tests/BoostTest/vehicle_test.cpp.o

Code/Tests/BoostTest/vehicle_test.i: Code/Tests/BoostTest/vehicle_test.cpp.i

.PHONY : Code/Tests/BoostTest/vehicle_test.i

# target to preprocess a source file
Code/Tests/BoostTest/vehicle_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/vehicle_test.cpp.i
.PHONY : Code/Tests/BoostTest/vehicle_test.cpp.i

Code/Tests/BoostTest/vehicle_test.s: Code/Tests/BoostTest/vehicle_test.cpp.s

.PHONY : Code/Tests/BoostTest/vehicle_test.s

# target to generate assembly for a file
Code/Tests/BoostTest/vehicle_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Tests/BoostTest/vehicle_test.cpp.s
.PHONY : Code/Tests/BoostTest/vehicle_test.cpp.s

Code/Vehicles/car.o: Code/Vehicles/car.cpp.o

.PHONY : Code/Vehicles/car.o

# target to build an object file
Code/Vehicles/car.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/car.cpp.o
.PHONY : Code/Vehicles/car.cpp.o

Code/Vehicles/car.i: Code/Vehicles/car.cpp.i

.PHONY : Code/Vehicles/car.i

# target to preprocess a source file
Code/Vehicles/car.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/car.cpp.i
.PHONY : Code/Vehicles/car.cpp.i

Code/Vehicles/car.s: Code/Vehicles/car.cpp.s

.PHONY : Code/Vehicles/car.s

# target to generate assembly for a file
Code/Vehicles/car.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/car.cpp.s
.PHONY : Code/Vehicles/car.cpp.s

Code/Vehicles/truck.o: Code/Vehicles/truck.cpp.o

.PHONY : Code/Vehicles/truck.o

# target to build an object file
Code/Vehicles/truck.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/truck.cpp.o
.PHONY : Code/Vehicles/truck.cpp.o

Code/Vehicles/truck.i: Code/Vehicles/truck.cpp.i

.PHONY : Code/Vehicles/truck.i

# target to preprocess a source file
Code/Vehicles/truck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/truck.cpp.i
.PHONY : Code/Vehicles/truck.cpp.i

Code/Vehicles/truck.s: Code/Vehicles/truck.cpp.s

.PHONY : Code/Vehicles/truck.s

# target to generate assembly for a file
Code/Vehicles/truck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/truck.cpp.s
.PHONY : Code/Vehicles/truck.cpp.s

Code/Vehicles/vehicle.o: Code/Vehicles/vehicle.cpp.o

.PHONY : Code/Vehicles/vehicle.o

# target to build an object file
Code/Vehicles/vehicle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/vehicle.cpp.o
.PHONY : Code/Vehicles/vehicle.cpp.o

Code/Vehicles/vehicle.i: Code/Vehicles/vehicle.cpp.i

.PHONY : Code/Vehicles/vehicle.i

# target to preprocess a source file
Code/Vehicles/vehicle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/vehicle.cpp.i
.PHONY : Code/Vehicles/vehicle.cpp.i

Code/Vehicles/vehicle.s: Code/Vehicles/vehicle.cpp.s

.PHONY : Code/Vehicles/vehicle.s

# target to generate assembly for a file
Code/Vehicles/vehicle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/vehicle.cpp.s
.PHONY : Code/Vehicles/vehicle.cpp.s

Code/Vehicles/vehicle_factory.o: Code/Vehicles/vehicle_factory.cpp.o

.PHONY : Code/Vehicles/vehicle_factory.o

# target to build an object file
Code/Vehicles/vehicle_factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/vehicle_factory.cpp.o
.PHONY : Code/Vehicles/vehicle_factory.cpp.o

Code/Vehicles/vehicle_factory.i: Code/Vehicles/vehicle_factory.cpp.i

.PHONY : Code/Vehicles/vehicle_factory.i

# target to preprocess a source file
Code/Vehicles/vehicle_factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/vehicle_factory.cpp.i
.PHONY : Code/Vehicles/vehicle_factory.cpp.i

Code/Vehicles/vehicle_factory.s: Code/Vehicles/vehicle_factory.cpp.s

.PHONY : Code/Vehicles/vehicle_factory.s

# target to generate assembly for a file
Code/Vehicles/vehicle_factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/vehicle_factory.cpp.s
.PHONY : Code/Vehicles/vehicle_factory.cpp.s

Code/adding_helper.o: Code/adding_helper.cpp.o

.PHONY : Code/adding_helper.o

# target to build an object file
Code/adding_helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/adding_helper.cpp.o
.PHONY : Code/adding_helper.cpp.o

Code/adding_helper.i: Code/adding_helper.cpp.i

.PHONY : Code/adding_helper.i

# target to preprocess a source file
Code/adding_helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/adding_helper.cpp.i
.PHONY : Code/adding_helper.cpp.i

Code/adding_helper.s: Code/adding_helper.cpp.s

.PHONY : Code/adding_helper.s

# target to generate assembly for a file
Code/adding_helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/adding_helper.cpp.s
.PHONY : Code/adding_helper.cpp.s

Code/asset_manager.o: Code/asset_manager.cpp.o

.PHONY : Code/asset_manager.o

# target to build an object file
Code/asset_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/asset_manager.cpp.o
.PHONY : Code/asset_manager.cpp.o

Code/asset_manager.i: Code/asset_manager.cpp.i

.PHONY : Code/asset_manager.i

# target to preprocess a source file
Code/asset_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/asset_manager.cpp.i
.PHONY : Code/asset_manager.cpp.i

Code/asset_manager.s: Code/asset_manager.cpp.s

.PHONY : Code/asset_manager.s

# target to generate assembly for a file
Code/asset_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/asset_manager.cpp.s
.PHONY : Code/asset_manager.cpp.s

Code/button.o: Code/button.cpp.o

.PHONY : Code/button.o

# target to build an object file
Code/button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/button.cpp.o
.PHONY : Code/button.cpp.o

Code/button.i: Code/button.cpp.i

.PHONY : Code/button.i

# target to preprocess a source file
Code/button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/button.cpp.i
.PHONY : Code/button.cpp.i

Code/button.s: Code/button.cpp.s

.PHONY : Code/button.s

# target to generate assembly for a file
Code/button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/button.cpp.s
.PHONY : Code/button.cpp.s

Code/camera.o: Code/camera.cpp.o

.PHONY : Code/camera.o

# target to build an object file
Code/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/camera.cpp.o
.PHONY : Code/camera.cpp.o

Code/camera.i: Code/camera.cpp.i

.PHONY : Code/camera.i

# target to preprocess a source file
Code/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/camera.cpp.i
.PHONY : Code/camera.cpp.i

Code/camera.s: Code/camera.cpp.s

.PHONY : Code/camera.s

# target to generate assembly for a file
Code/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/camera.cpp.s
.PHONY : Code/camera.cpp.s

Code/cameras_subject.o: Code/cameras_subject.cpp.o

.PHONY : Code/cameras_subject.o

# target to build an object file
Code/cameras_subject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/cameras_subject.cpp.o
.PHONY : Code/cameras_subject.cpp.o

Code/cameras_subject.i: Code/cameras_subject.cpp.i

.PHONY : Code/cameras_subject.i

# target to preprocess a source file
Code/cameras_subject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/cameras_subject.cpp.i
.PHONY : Code/cameras_subject.cpp.i

Code/cameras_subject.s: Code/cameras_subject.cpp.s

.PHONY : Code/cameras_subject.s

# target to generate assembly for a file
Code/cameras_subject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/cameras_subject.cpp.s
.PHONY : Code/cameras_subject.cpp.s

Code/cameras_view.o: Code/cameras_view.cpp.o

.PHONY : Code/cameras_view.o

# target to build an object file
Code/cameras_view.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/cameras_view.cpp.o
.PHONY : Code/cameras_view.cpp.o

Code/cameras_view.i: Code/cameras_view.cpp.i

.PHONY : Code/cameras_view.i

# target to preprocess a source file
Code/cameras_view.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/cameras_view.cpp.i
.PHONY : Code/cameras_view.cpp.i

Code/cameras_view.s: Code/cameras_view.cpp.s

.PHONY : Code/cameras_view.s

# target to generate assembly for a file
Code/cameras_view.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/cameras_view.cpp.s
.PHONY : Code/cameras_view.cpp.s

Code/cell.o: Code/cell.cpp.o

.PHONY : Code/cell.o

# target to build an object file
Code/cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/cell.cpp.o
.PHONY : Code/cell.cpp.o

Code/cell.i: Code/cell.cpp.i

.PHONY : Code/cell.i

# target to preprocess a source file
Code/cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/cell.cpp.i
.PHONY : Code/cell.cpp.i

Code/cell.s: Code/cell.cpp.s

.PHONY : Code/cell.s

# target to generate assembly for a file
Code/cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/cell.cpp.s
.PHONY : Code/cell.cpp.s

Code/converter.o: Code/converter.cpp.o

.PHONY : Code/converter.o

# target to build an object file
Code/converter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/converter.cpp.o
.PHONY : Code/converter.cpp.o

Code/converter.i: Code/converter.cpp.i

.PHONY : Code/converter.i

# target to preprocess a source file
Code/converter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/converter.cpp.i
.PHONY : Code/converter.cpp.i

Code/converter.s: Code/converter.cpp.s

.PHONY : Code/converter.s

# target to generate assembly for a file
Code/converter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/converter.cpp.s
.PHONY : Code/converter.cpp.s

Code/creator_handler.o: Code/creator_handler.cpp.o

.PHONY : Code/creator_handler.o

# target to build an object file
Code/creator_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/creator_handler.cpp.o
.PHONY : Code/creator_handler.cpp.o

Code/creator_handler.i: Code/creator_handler.cpp.i

.PHONY : Code/creator_handler.i

# target to preprocess a source file
Code/creator_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/creator_handler.cpp.i
.PHONY : Code/creator_handler.cpp.i

Code/creator_handler.s: Code/creator_handler.cpp.s

.PHONY : Code/creator_handler.s

# target to generate assembly for a file
Code/creator_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/creator_handler.cpp.s
.PHONY : Code/creator_handler.cpp.s

Code/creator_state.o: Code/creator_state.cpp.o

.PHONY : Code/creator_state.o

# target to build an object file
Code/creator_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/creator_state.cpp.o
.PHONY : Code/creator_state.cpp.o

Code/creator_state.i: Code/creator_state.cpp.i

.PHONY : Code/creator_state.i

# target to preprocess a source file
Code/creator_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/creator_state.cpp.i
.PHONY : Code/creator_state.cpp.i

Code/creator_state.s: Code/creator_state.cpp.s

.PHONY : Code/creator_state.s

# target to generate assembly for a file
Code/creator_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/creator_state.cpp.s
.PHONY : Code/creator_state.cpp.s

Code/creator_subject.o: Code/creator_subject.cpp.o

.PHONY : Code/creator_subject.o

# target to build an object file
Code/creator_subject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/creator_subject.cpp.o
.PHONY : Code/creator_subject.cpp.o

Code/creator_subject.i: Code/creator_subject.cpp.i

.PHONY : Code/creator_subject.i

# target to preprocess a source file
Code/creator_subject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/creator_subject.cpp.i
.PHONY : Code/creator_subject.cpp.i

Code/creator_subject.s: Code/creator_subject.cpp.s

.PHONY : Code/creator_subject.s

# target to generate assembly for a file
Code/creator_subject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/creator_subject.cpp.s
.PHONY : Code/creator_subject.cpp.s

Code/drawing_helper.o: Code/drawing_helper.cpp.o

.PHONY : Code/drawing_helper.o

# target to build an object file
Code/drawing_helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/drawing_helper.cpp.o
.PHONY : Code/drawing_helper.cpp.o

Code/drawing_helper.i: Code/drawing_helper.cpp.i

.PHONY : Code/drawing_helper.i

# target to preprocess a source file
Code/drawing_helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/drawing_helper.cpp.i
.PHONY : Code/drawing_helper.cpp.i

Code/drawing_helper.s: Code/drawing_helper.cpp.s

.PHONY : Code/drawing_helper.s

# target to generate assembly for a file
Code/drawing_helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/drawing_helper.cpp.s
.PHONY : Code/drawing_helper.cpp.s

Code/file_finder.o: Code/file_finder.cpp.o

.PHONY : Code/file_finder.o

# target to build an object file
Code/file_finder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/file_finder.cpp.o
.PHONY : Code/file_finder.cpp.o

Code/file_finder.i: Code/file_finder.cpp.i

.PHONY : Code/file_finder.i

# target to preprocess a source file
Code/file_finder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/file_finder.cpp.i
.PHONY : Code/file_finder.cpp.i

Code/file_finder.s: Code/file_finder.cpp.s

.PHONY : Code/file_finder.s

# target to generate assembly for a file
Code/file_finder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/file_finder.cpp.s
.PHONY : Code/file_finder.cpp.s

Code/grid.o: Code/grid.cpp.o

.PHONY : Code/grid.o

# target to build an object file
Code/grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/grid.cpp.o
.PHONY : Code/grid.cpp.o

Code/grid.i: Code/grid.cpp.i

.PHONY : Code/grid.i

# target to preprocess a source file
Code/grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/grid.cpp.i
.PHONY : Code/grid.cpp.i

Code/grid.s: Code/grid.cpp.s

.PHONY : Code/grid.s

# target to generate assembly for a file
Code/grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/grid.cpp.s
.PHONY : Code/grid.cpp.s

Code/init_create_state.o: Code/init_create_state.cpp.o

.PHONY : Code/init_create_state.o

# target to build an object file
Code/init_create_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/init_create_state.cpp.o
.PHONY : Code/init_create_state.cpp.o

Code/init_create_state.i: Code/init_create_state.cpp.i

.PHONY : Code/init_create_state.i

# target to preprocess a source file
Code/init_create_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/init_create_state.cpp.i
.PHONY : Code/init_create_state.cpp.i

Code/init_create_state.s: Code/init_create_state.cpp.s

.PHONY : Code/init_create_state.s

# target to generate assembly for a file
Code/init_create_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/init_create_state.cpp.s
.PHONY : Code/init_create_state.cpp.s

Code/init_create_state_helper.o: Code/init_create_state_helper.cpp.o

.PHONY : Code/init_create_state_helper.o

# target to build an object file
Code/init_create_state_helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/init_create_state_helper.cpp.o
.PHONY : Code/init_create_state_helper.cpp.o

Code/init_create_state_helper.i: Code/init_create_state_helper.cpp.i

.PHONY : Code/init_create_state_helper.i

# target to preprocess a source file
Code/init_create_state_helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/init_create_state_helper.cpp.i
.PHONY : Code/init_create_state_helper.cpp.i

Code/init_create_state_helper.s: Code/init_create_state_helper.cpp.s

.PHONY : Code/init_create_state_helper.s

# target to generate assembly for a file
Code/init_create_state_helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/init_create_state_helper.cpp.s
.PHONY : Code/init_create_state_helper.cpp.s

Code/input_manager.o: Code/input_manager.cpp.o

.PHONY : Code/input_manager.o

# target to build an object file
Code/input_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/input_manager.cpp.o
.PHONY : Code/input_manager.cpp.o

Code/input_manager.i: Code/input_manager.cpp.i

.PHONY : Code/input_manager.i

# target to preprocess a source file
Code/input_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/input_manager.cpp.i
.PHONY : Code/input_manager.cpp.i

Code/input_manager.s: Code/input_manager.cpp.s

.PHONY : Code/input_manager.s

# target to generate assembly for a file
Code/input_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/input_manager.cpp.s
.PHONY : Code/input_manager.cpp.s

Code/load_state.o: Code/load_state.cpp.o

.PHONY : Code/load_state.o

# target to build an object file
Code/load_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/load_state.cpp.o
.PHONY : Code/load_state.cpp.o

Code/load_state.i: Code/load_state.cpp.i

.PHONY : Code/load_state.i

# target to preprocess a source file
Code/load_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/load_state.cpp.i
.PHONY : Code/load_state.cpp.i

Code/load_state.s: Code/load_state.cpp.s

.PHONY : Code/load_state.s

# target to generate assembly for a file
Code/load_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/load_state.cpp.s
.PHONY : Code/load_state.cpp.s

Code/main_menu_state.o: Code/main_menu_state.cpp.o

.PHONY : Code/main_menu_state.o

# target to build an object file
Code/main_menu_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/main_menu_state.cpp.o
.PHONY : Code/main_menu_state.cpp.o

Code/main_menu_state.i: Code/main_menu_state.cpp.i

.PHONY : Code/main_menu_state.i

# target to preprocess a source file
Code/main_menu_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/main_menu_state.cpp.i
.PHONY : Code/main_menu_state.cpp.i

Code/main_menu_state.s: Code/main_menu_state.cpp.s

.PHONY : Code/main_menu_state.s

# target to generate assembly for a file
Code/main_menu_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/main_menu_state.cpp.s
.PHONY : Code/main_menu_state.cpp.s

Code/map_view.o: Code/map_view.cpp.o

.PHONY : Code/map_view.o

# target to build an object file
Code/map_view.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/map_view.cpp.o
.PHONY : Code/map_view.cpp.o

Code/map_view.i: Code/map_view.cpp.i

.PHONY : Code/map_view.i

# target to preprocess a source file
Code/map_view.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/map_view.cpp.i
.PHONY : Code/map_view.cpp.i

Code/map_view.s: Code/map_view.cpp.s

.PHONY : Code/map_view.s

# target to generate assembly for a file
Code/map_view.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/map_view.cpp.s
.PHONY : Code/map_view.cpp.s

Code/road_builder_helper.o: Code/road_builder_helper.cpp.o

.PHONY : Code/road_builder_helper.o

# target to build an object file
Code/road_builder_helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/road_builder_helper.cpp.o
.PHONY : Code/road_builder_helper.cpp.o

Code/road_builder_helper.i: Code/road_builder_helper.cpp.i

.PHONY : Code/road_builder_helper.i

# target to preprocess a source file
Code/road_builder_helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/road_builder_helper.cpp.i
.PHONY : Code/road_builder_helper.cpp.i

Code/road_builder_helper.s: Code/road_builder_helper.cpp.s

.PHONY : Code/road_builder_helper.s

# target to generate assembly for a file
Code/road_builder_helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/road_builder_helper.cpp.s
.PHONY : Code/road_builder_helper.cpp.s

Code/save_state.o: Code/save_state.cpp.o

.PHONY : Code/save_state.o

# target to build an object file
Code/save_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/save_state.cpp.o
.PHONY : Code/save_state.cpp.o

Code/save_state.i: Code/save_state.cpp.i

.PHONY : Code/save_state.i

# target to preprocess a source file
Code/save_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/save_state.cpp.i
.PHONY : Code/save_state.cpp.i

Code/save_state.s: Code/save_state.cpp.s

.PHONY : Code/save_state.s

# target to generate assembly for a file
Code/save_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/save_state.cpp.s
.PHONY : Code/save_state.cpp.s

Code/simulation_handler.o: Code/simulation_handler.cpp.o

.PHONY : Code/simulation_handler.o

# target to build an object file
Code/simulation_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/simulation_handler.cpp.o
.PHONY : Code/simulation_handler.cpp.o

Code/simulation_handler.i: Code/simulation_handler.cpp.i

.PHONY : Code/simulation_handler.i

# target to preprocess a source file
Code/simulation_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/simulation_handler.cpp.i
.PHONY : Code/simulation_handler.cpp.i

Code/simulation_handler.s: Code/simulation_handler.cpp.s

.PHONY : Code/simulation_handler.s

# target to generate assembly for a file
Code/simulation_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/simulation_handler.cpp.s
.PHONY : Code/simulation_handler.cpp.s

Code/simulation_subject.o: Code/simulation_subject.cpp.o

.PHONY : Code/simulation_subject.o

# target to build an object file
Code/simulation_subject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/simulation_subject.cpp.o
.PHONY : Code/simulation_subject.cpp.o

Code/simulation_subject.i: Code/simulation_subject.cpp.i

.PHONY : Code/simulation_subject.i

# target to preprocess a source file
Code/simulation_subject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/simulation_subject.cpp.i
.PHONY : Code/simulation_subject.cpp.i

Code/simulation_subject.s: Code/simulation_subject.cpp.s

.PHONY : Code/simulation_subject.s

# target to generate assembly for a file
Code/simulation_subject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/simulation_subject.cpp.s
.PHONY : Code/simulation_subject.cpp.s

Code/simulator.o: Code/simulator.cpp.o

.PHONY : Code/simulator.o

# target to build an object file
Code/simulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/simulator.cpp.o
.PHONY : Code/simulator.cpp.o

Code/simulator.i: Code/simulator.cpp.i

.PHONY : Code/simulator.i

# target to preprocess a source file
Code/simulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/simulator.cpp.i
.PHONY : Code/simulator.cpp.i

Code/simulator.s: Code/simulator.cpp.s

.PHONY : Code/simulator.s

# target to generate assembly for a file
Code/simulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/simulator.cpp.s
.PHONY : Code/simulator.cpp.s

Code/splash_state.o: Code/splash_state.cpp.o

.PHONY : Code/splash_state.o

# target to build an object file
Code/splash_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/splash_state.cpp.o
.PHONY : Code/splash_state.cpp.o

Code/splash_state.i: Code/splash_state.cpp.i

.PHONY : Code/splash_state.i

# target to preprocess a source file
Code/splash_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/splash_state.cpp.i
.PHONY : Code/splash_state.cpp.i

Code/splash_state.s: Code/splash_state.cpp.s

.PHONY : Code/splash_state.s

# target to generate assembly for a file
Code/splash_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/splash_state.cpp.s
.PHONY : Code/splash_state.cpp.s

Code/state_machine.o: Code/state_machine.cpp.o

.PHONY : Code/state_machine.o

# target to build an object file
Code/state_machine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/state_machine.cpp.o
.PHONY : Code/state_machine.cpp.o

Code/state_machine.i: Code/state_machine.cpp.i

.PHONY : Code/state_machine.i

# target to preprocess a source file
Code/state_machine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/state_machine.cpp.i
.PHONY : Code/state_machine.cpp.i

Code/state_machine.s: Code/state_machine.cpp.s

.PHONY : Code/state_machine.s

# target to generate assembly for a file
Code/state_machine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/state_machine.cpp.s
.PHONY : Code/state_machine.cpp.s

Code/tools_subject.o: Code/tools_subject.cpp.o

.PHONY : Code/tools_subject.o

# target to build an object file
Code/tools_subject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/tools_subject.cpp.o
.PHONY : Code/tools_subject.cpp.o

Code/tools_subject.i: Code/tools_subject.cpp.i

.PHONY : Code/tools_subject.i

# target to preprocess a source file
Code/tools_subject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/tools_subject.cpp.i
.PHONY : Code/tools_subject.cpp.i

Code/tools_subject.s: Code/tools_subject.cpp.s

.PHONY : Code/tools_subject.s

# target to generate assembly for a file
Code/tools_subject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/tools_subject.cpp.s
.PHONY : Code/tools_subject.cpp.s

Code/tools_view.o: Code/tools_view.cpp.o

.PHONY : Code/tools_view.o

# target to build an object file
Code/tools_view.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/tools_view.cpp.o
.PHONY : Code/tools_view.cpp.o

Code/tools_view.i: Code/tools_view.cpp.i

.PHONY : Code/tools_view.i

# target to preprocess a source file
Code/tools_view.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/tools_view.cpp.i
.PHONY : Code/tools_view.cpp.i

Code/tools_view.s: Code/tools_view.cpp.s

.PHONY : Code/tools_view.s

# target to generate assembly for a file
Code/tools_view.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/tools_view.cpp.s
.PHONY : Code/tools_view.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CityTrafficSimulator"
	@echo "... Code/Tests/BoostTest/converter_test.o"
	@echo "... Code/Tests/BoostTest/converter_test.i"
	@echo "... Code/Tests/BoostTest/converter_test.s"
	@echo "... Code/Tests/BoostTest/file_finder_test.o"
	@echo "... Code/Tests/BoostTest/file_finder_test.i"
	@echo "... Code/Tests/BoostTest/file_finder_test.s"
	@echo "... Code/Tests/BoostTest/init_create_state_helper_test.o"
	@echo "... Code/Tests/BoostTest/init_create_state_helper_test.i"
	@echo "... Code/Tests/BoostTest/init_create_state_helper_test.s"
	@echo "... Code/Tests/BoostTest/main_menu_state_test.o"
	@echo "... Code/Tests/BoostTest/main_menu_state_test.i"
	@echo "... Code/Tests/BoostTest/main_menu_state_test.s"
	@echo "... Code/Tests/BoostTest/map_view_test.o"
	@echo "... Code/Tests/BoostTest/map_view_test.i"
	@echo "... Code/Tests/BoostTest/map_view_test.s"
	@echo "... Code/Tests/BoostTest/vehicle_test.o"
	@echo "... Code/Tests/BoostTest/vehicle_test.i"
	@echo "... Code/Tests/BoostTest/vehicle_test.s"
	@echo "... Code/Vehicles/car.o"
	@echo "... Code/Vehicles/car.i"
	@echo "... Code/Vehicles/car.s"
	@echo "... Code/Vehicles/truck.o"
	@echo "... Code/Vehicles/truck.i"
	@echo "... Code/Vehicles/truck.s"
	@echo "... Code/Vehicles/vehicle.o"
	@echo "... Code/Vehicles/vehicle.i"
	@echo "... Code/Vehicles/vehicle.s"
	@echo "... Code/Vehicles/vehicle_factory.o"
	@echo "... Code/Vehicles/vehicle_factory.i"
	@echo "... Code/Vehicles/vehicle_factory.s"
	@echo "... Code/adding_helper.o"
	@echo "... Code/adding_helper.i"
	@echo "... Code/adding_helper.s"
	@echo "... Code/asset_manager.o"
	@echo "... Code/asset_manager.i"
	@echo "... Code/asset_manager.s"
	@echo "... Code/button.o"
	@echo "... Code/button.i"
	@echo "... Code/button.s"
	@echo "... Code/camera.o"
	@echo "... Code/camera.i"
	@echo "... Code/camera.s"
	@echo "... Code/cameras_subject.o"
	@echo "... Code/cameras_subject.i"
	@echo "... Code/cameras_subject.s"
	@echo "... Code/cameras_view.o"
	@echo "... Code/cameras_view.i"
	@echo "... Code/cameras_view.s"
	@echo "... Code/cell.o"
	@echo "... Code/cell.i"
	@echo "... Code/cell.s"
	@echo "... Code/converter.o"
	@echo "... Code/converter.i"
	@echo "... Code/converter.s"
	@echo "... Code/creator_handler.o"
	@echo "... Code/creator_handler.i"
	@echo "... Code/creator_handler.s"
	@echo "... Code/creator_state.o"
	@echo "... Code/creator_state.i"
	@echo "... Code/creator_state.s"
	@echo "... Code/creator_subject.o"
	@echo "... Code/creator_subject.i"
	@echo "... Code/creator_subject.s"
	@echo "... Code/drawing_helper.o"
	@echo "... Code/drawing_helper.i"
	@echo "... Code/drawing_helper.s"
	@echo "... Code/file_finder.o"
	@echo "... Code/file_finder.i"
	@echo "... Code/file_finder.s"
	@echo "... Code/grid.o"
	@echo "... Code/grid.i"
	@echo "... Code/grid.s"
	@echo "... Code/init_create_state.o"
	@echo "... Code/init_create_state.i"
	@echo "... Code/init_create_state.s"
	@echo "... Code/init_create_state_helper.o"
	@echo "... Code/init_create_state_helper.i"
	@echo "... Code/init_create_state_helper.s"
	@echo "... Code/input_manager.o"
	@echo "... Code/input_manager.i"
	@echo "... Code/input_manager.s"
	@echo "... Code/load_state.o"
	@echo "... Code/load_state.i"
	@echo "... Code/load_state.s"
	@echo "... Code/main_menu_state.o"
	@echo "... Code/main_menu_state.i"
	@echo "... Code/main_menu_state.s"
	@echo "... Code/map_view.o"
	@echo "... Code/map_view.i"
	@echo "... Code/map_view.s"
	@echo "... Code/road_builder_helper.o"
	@echo "... Code/road_builder_helper.i"
	@echo "... Code/road_builder_helper.s"
	@echo "... Code/save_state.o"
	@echo "... Code/save_state.i"
	@echo "... Code/save_state.s"
	@echo "... Code/simulation_handler.o"
	@echo "... Code/simulation_handler.i"
	@echo "... Code/simulation_handler.s"
	@echo "... Code/simulation_subject.o"
	@echo "... Code/simulation_subject.i"
	@echo "... Code/simulation_subject.s"
	@echo "... Code/simulator.o"
	@echo "... Code/simulator.i"
	@echo "... Code/simulator.s"
	@echo "... Code/splash_state.o"
	@echo "... Code/splash_state.i"
	@echo "... Code/splash_state.s"
	@echo "... Code/state_machine.o"
	@echo "... Code/state_machine.i"
	@echo "... Code/state_machine.s"
	@echo "... Code/tools_subject.o"
	@echo "... Code/tools_subject.i"
	@echo "... Code/tools_subject.s"
	@echo "... Code/tools_view.o"
	@echo "... Code/tools_view.i"
	@echo "... Code/tools_view.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

