# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR/CMakeFiles /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/erykmroczko/Documents/Studia/ZPR/CityTrafficSimulator_ZPR/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CityTrafficSimulator

# Build rule for target.
CityTrafficSimulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CityTrafficSimulator
.PHONY : CityTrafficSimulator

# fast build rule for target.
CityTrafficSimulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/build
.PHONY : CityTrafficSimulator/fast

Code/AssetManager.o: Code/AssetManager.cpp.o

.PHONY : Code/AssetManager.o

# target to build an object file
Code/AssetManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/AssetManager.cpp.o
.PHONY : Code/AssetManager.cpp.o

Code/AssetManager.i: Code/AssetManager.cpp.i

.PHONY : Code/AssetManager.i

# target to preprocess a source file
Code/AssetManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/AssetManager.cpp.i
.PHONY : Code/AssetManager.cpp.i

Code/AssetManager.s: Code/AssetManager.cpp.s

.PHONY : Code/AssetManager.s

# target to generate assembly for a file
Code/AssetManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/AssetManager.cpp.s
.PHONY : Code/AssetManager.cpp.s

Code/Button.o: Code/Button.cpp.o

.PHONY : Code/Button.o

# target to build an object file
Code/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Button.cpp.o
.PHONY : Code/Button.cpp.o

Code/Button.i: Code/Button.cpp.i

.PHONY : Code/Button.i

# target to preprocess a source file
Code/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Button.cpp.i
.PHONY : Code/Button.cpp.i

Code/Button.s: Code/Button.cpp.s

.PHONY : Code/Button.s

# target to generate assembly for a file
Code/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Button.cpp.s
.PHONY : Code/Button.cpp.s

Code/CamerasSubject.o: Code/CamerasSubject.cpp.o

.PHONY : Code/CamerasSubject.o

# target to build an object file
Code/CamerasSubject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CamerasSubject.cpp.o
.PHONY : Code/CamerasSubject.cpp.o

Code/CamerasSubject.i: Code/CamerasSubject.cpp.i

.PHONY : Code/CamerasSubject.i

# target to preprocess a source file
Code/CamerasSubject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CamerasSubject.cpp.i
.PHONY : Code/CamerasSubject.cpp.i

Code/CamerasSubject.s: Code/CamerasSubject.cpp.s

.PHONY : Code/CamerasSubject.s

# target to generate assembly for a file
Code/CamerasSubject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CamerasSubject.cpp.s
.PHONY : Code/CamerasSubject.cpp.s

Code/CamerasView.o: Code/CamerasView.cpp.o

.PHONY : Code/CamerasView.o

# target to build an object file
Code/CamerasView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CamerasView.cpp.o
.PHONY : Code/CamerasView.cpp.o

Code/CamerasView.i: Code/CamerasView.cpp.i

.PHONY : Code/CamerasView.i

# target to preprocess a source file
Code/CamerasView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CamerasView.cpp.i
.PHONY : Code/CamerasView.cpp.i

Code/CamerasView.s: Code/CamerasView.cpp.s

.PHONY : Code/CamerasView.s

# target to generate assembly for a file
Code/CamerasView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CamerasView.cpp.s
.PHONY : Code/CamerasView.cpp.s

Code/Cell.o: Code/Cell.cpp.o

.PHONY : Code/Cell.o

# target to build an object file
Code/Cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Cell.cpp.o
.PHONY : Code/Cell.cpp.o

Code/Cell.i: Code/Cell.cpp.i

.PHONY : Code/Cell.i

# target to preprocess a source file
Code/Cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Cell.cpp.i
.PHONY : Code/Cell.cpp.i

Code/Cell.s: Code/Cell.cpp.s

.PHONY : Code/Cell.s

# target to generate assembly for a file
Code/Cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Cell.cpp.s
.PHONY : Code/Cell.cpp.s

Code/CreatorHandler.o: Code/CreatorHandler.cpp.o

.PHONY : Code/CreatorHandler.o

# target to build an object file
Code/CreatorHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorHandler.cpp.o
.PHONY : Code/CreatorHandler.cpp.o

Code/CreatorHandler.i: Code/CreatorHandler.cpp.i

.PHONY : Code/CreatorHandler.i

# target to preprocess a source file
Code/CreatorHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorHandler.cpp.i
.PHONY : Code/CreatorHandler.cpp.i

Code/CreatorHandler.s: Code/CreatorHandler.cpp.s

.PHONY : Code/CreatorHandler.s

# target to generate assembly for a file
Code/CreatorHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorHandler.cpp.s
.PHONY : Code/CreatorHandler.cpp.s

Code/CreatorState.o: Code/CreatorState.cpp.o

.PHONY : Code/CreatorState.o

# target to build an object file
Code/CreatorState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorState.cpp.o
.PHONY : Code/CreatorState.cpp.o

Code/CreatorState.i: Code/CreatorState.cpp.i

.PHONY : Code/CreatorState.i

# target to preprocess a source file
Code/CreatorState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorState.cpp.i
.PHONY : Code/CreatorState.cpp.i

Code/CreatorState.s: Code/CreatorState.cpp.s

.PHONY : Code/CreatorState.s

# target to generate assembly for a file
Code/CreatorState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorState.cpp.s
.PHONY : Code/CreatorState.cpp.s

Code/CreatorSubject.o: Code/CreatorSubject.cpp.o

.PHONY : Code/CreatorSubject.o

# target to build an object file
Code/CreatorSubject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorSubject.cpp.o
.PHONY : Code/CreatorSubject.cpp.o

Code/CreatorSubject.i: Code/CreatorSubject.cpp.i

.PHONY : Code/CreatorSubject.i

# target to preprocess a source file
Code/CreatorSubject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorSubject.cpp.i
.PHONY : Code/CreatorSubject.cpp.i

Code/CreatorSubject.s: Code/CreatorSubject.cpp.s

.PHONY : Code/CreatorSubject.s

# target to generate assembly for a file
Code/CreatorSubject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/CreatorSubject.cpp.s
.PHONY : Code/CreatorSubject.cpp.s

Code/FileFinder.o: Code/FileFinder.cpp.o

.PHONY : Code/FileFinder.o

# target to build an object file
Code/FileFinder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/FileFinder.cpp.o
.PHONY : Code/FileFinder.cpp.o

Code/FileFinder.i: Code/FileFinder.cpp.i

.PHONY : Code/FileFinder.i

# target to preprocess a source file
Code/FileFinder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/FileFinder.cpp.i
.PHONY : Code/FileFinder.cpp.i

Code/FileFinder.s: Code/FileFinder.cpp.s

.PHONY : Code/FileFinder.s

# target to generate assembly for a file
Code/FileFinder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/FileFinder.cpp.s
.PHONY : Code/FileFinder.cpp.s

Code/Grid.o: Code/Grid.cpp.o

.PHONY : Code/Grid.o

# target to build an object file
Code/Grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Grid.cpp.o
.PHONY : Code/Grid.cpp.o

Code/Grid.i: Code/Grid.cpp.i

.PHONY : Code/Grid.i

# target to preprocess a source file
Code/Grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Grid.cpp.i
.PHONY : Code/Grid.cpp.i

Code/Grid.s: Code/Grid.cpp.s

.PHONY : Code/Grid.s

# target to generate assembly for a file
Code/Grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Grid.cpp.s
.PHONY : Code/Grid.cpp.s

Code/InitCreateState.o: Code/InitCreateState.cpp.o

.PHONY : Code/InitCreateState.o

# target to build an object file
Code/InitCreateState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/InitCreateState.cpp.o
.PHONY : Code/InitCreateState.cpp.o

Code/InitCreateState.i: Code/InitCreateState.cpp.i

.PHONY : Code/InitCreateState.i

# target to preprocess a source file
Code/InitCreateState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/InitCreateState.cpp.i
.PHONY : Code/InitCreateState.cpp.i

Code/InitCreateState.s: Code/InitCreateState.cpp.s

.PHONY : Code/InitCreateState.s

# target to generate assembly for a file
Code/InitCreateState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/InitCreateState.cpp.s
.PHONY : Code/InitCreateState.cpp.s

Code/InputManager.o: Code/InputManager.cpp.o

.PHONY : Code/InputManager.o

# target to build an object file
Code/InputManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/InputManager.cpp.o
.PHONY : Code/InputManager.cpp.o

Code/InputManager.i: Code/InputManager.cpp.i

.PHONY : Code/InputManager.i

# target to preprocess a source file
Code/InputManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/InputManager.cpp.i
.PHONY : Code/InputManager.cpp.i

Code/InputManager.s: Code/InputManager.cpp.s

.PHONY : Code/InputManager.s

# target to generate assembly for a file
Code/InputManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/InputManager.cpp.s
.PHONY : Code/InputManager.cpp.s

Code/LoadDemo.o: Code/LoadDemo.cpp.o

.PHONY : Code/LoadDemo.o

# target to build an object file
Code/LoadDemo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/LoadDemo.cpp.o
.PHONY : Code/LoadDemo.cpp.o

Code/LoadDemo.i: Code/LoadDemo.cpp.i

.PHONY : Code/LoadDemo.i

# target to preprocess a source file
Code/LoadDemo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/LoadDemo.cpp.i
.PHONY : Code/LoadDemo.cpp.i

Code/LoadDemo.s: Code/LoadDemo.cpp.s

.PHONY : Code/LoadDemo.s

# target to generate assembly for a file
Code/LoadDemo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/LoadDemo.cpp.s
.PHONY : Code/LoadDemo.cpp.s

Code/LoadState.o: Code/LoadState.cpp.o

.PHONY : Code/LoadState.o

# target to build an object file
Code/LoadState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/LoadState.cpp.o
.PHONY : Code/LoadState.cpp.o

Code/LoadState.i: Code/LoadState.cpp.i

.PHONY : Code/LoadState.i

# target to preprocess a source file
Code/LoadState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/LoadState.cpp.i
.PHONY : Code/LoadState.cpp.i

Code/LoadState.s: Code/LoadState.cpp.s

.PHONY : Code/LoadState.s

# target to generate assembly for a file
Code/LoadState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/LoadState.cpp.s
.PHONY : Code/LoadState.cpp.s

Code/Main.o: Code/Main.cpp.o

.PHONY : Code/Main.o

# target to build an object file
Code/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Main.cpp.o
.PHONY : Code/Main.cpp.o

Code/Main.i: Code/Main.cpp.i

.PHONY : Code/Main.i

# target to preprocess a source file
Code/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Main.cpp.i
.PHONY : Code/Main.cpp.i

Code/Main.s: Code/Main.cpp.s

.PHONY : Code/Main.s

# target to generate assembly for a file
Code/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Main.cpp.s
.PHONY : Code/Main.cpp.s

Code/MainMenuState.o: Code/MainMenuState.cpp.o

.PHONY : Code/MainMenuState.o

# target to build an object file
Code/MainMenuState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/MainMenuState.cpp.o
.PHONY : Code/MainMenuState.cpp.o

Code/MainMenuState.i: Code/MainMenuState.cpp.i

.PHONY : Code/MainMenuState.i

# target to preprocess a source file
Code/MainMenuState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/MainMenuState.cpp.i
.PHONY : Code/MainMenuState.cpp.i

Code/MainMenuState.s: Code/MainMenuState.cpp.s

.PHONY : Code/MainMenuState.s

# target to generate assembly for a file
Code/MainMenuState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/MainMenuState.cpp.s
.PHONY : Code/MainMenuState.cpp.s

Code/MapView.o: Code/MapView.cpp.o

.PHONY : Code/MapView.o

# target to build an object file
Code/MapView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/MapView.cpp.o
.PHONY : Code/MapView.cpp.o

Code/MapView.i: Code/MapView.cpp.i

.PHONY : Code/MapView.i

# target to preprocess a source file
Code/MapView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/MapView.cpp.i
.PHONY : Code/MapView.cpp.i

Code/MapView.s: Code/MapView.cpp.s

.PHONY : Code/MapView.s

# target to generate assembly for a file
Code/MapView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/MapView.cpp.s
.PHONY : Code/MapView.cpp.s

Code/SaveState.o: Code/SaveState.cpp.o

.PHONY : Code/SaveState.o

# target to build an object file
Code/SaveState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SaveState.cpp.o
.PHONY : Code/SaveState.cpp.o

Code/SaveState.i: Code/SaveState.cpp.i

.PHONY : Code/SaveState.i

# target to preprocess a source file
Code/SaveState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SaveState.cpp.i
.PHONY : Code/SaveState.cpp.i

Code/SaveState.s: Code/SaveState.cpp.s

.PHONY : Code/SaveState.s

# target to generate assembly for a file
Code/SaveState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SaveState.cpp.s
.PHONY : Code/SaveState.cpp.s

Code/SimulationHandler.o: Code/SimulationHandler.cpp.o

.PHONY : Code/SimulationHandler.o

# target to build an object file
Code/SimulationHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SimulationHandler.cpp.o
.PHONY : Code/SimulationHandler.cpp.o

Code/SimulationHandler.i: Code/SimulationHandler.cpp.i

.PHONY : Code/SimulationHandler.i

# target to preprocess a source file
Code/SimulationHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SimulationHandler.cpp.i
.PHONY : Code/SimulationHandler.cpp.i

Code/SimulationHandler.s: Code/SimulationHandler.cpp.s

.PHONY : Code/SimulationHandler.s

# target to generate assembly for a file
Code/SimulationHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SimulationHandler.cpp.s
.PHONY : Code/SimulationHandler.cpp.s

Code/SimulationSubject.o: Code/SimulationSubject.cpp.o

.PHONY : Code/SimulationSubject.o

# target to build an object file
Code/SimulationSubject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SimulationSubject.cpp.o
.PHONY : Code/SimulationSubject.cpp.o

Code/SimulationSubject.i: Code/SimulationSubject.cpp.i

.PHONY : Code/SimulationSubject.i

# target to preprocess a source file
Code/SimulationSubject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SimulationSubject.cpp.i
.PHONY : Code/SimulationSubject.cpp.i

Code/SimulationSubject.s: Code/SimulationSubject.cpp.s

.PHONY : Code/SimulationSubject.s

# target to generate assembly for a file
Code/SimulationSubject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SimulationSubject.cpp.s
.PHONY : Code/SimulationSubject.cpp.s

Code/Simulator.o: Code/Simulator.cpp.o

.PHONY : Code/Simulator.o

# target to build an object file
Code/Simulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Simulator.cpp.o
.PHONY : Code/Simulator.cpp.o

Code/Simulator.i: Code/Simulator.cpp.i

.PHONY : Code/Simulator.i

# target to preprocess a source file
Code/Simulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Simulator.cpp.i
.PHONY : Code/Simulator.cpp.i

Code/Simulator.s: Code/Simulator.cpp.s

.PHONY : Code/Simulator.s

# target to generate assembly for a file
Code/Simulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Simulator.cpp.s
.PHONY : Code/Simulator.cpp.s

Code/SplashState.o: Code/SplashState.cpp.o

.PHONY : Code/SplashState.o

# target to build an object file
Code/SplashState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SplashState.cpp.o
.PHONY : Code/SplashState.cpp.o

Code/SplashState.i: Code/SplashState.cpp.i

.PHONY : Code/SplashState.i

# target to preprocess a source file
Code/SplashState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SplashState.cpp.i
.PHONY : Code/SplashState.cpp.i

Code/SplashState.s: Code/SplashState.cpp.s

.PHONY : Code/SplashState.s

# target to generate assembly for a file
Code/SplashState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/SplashState.cpp.s
.PHONY : Code/SplashState.cpp.s

Code/StateMachine.o: Code/StateMachine.cpp.o

.PHONY : Code/StateMachine.o

# target to build an object file
Code/StateMachine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/StateMachine.cpp.o
.PHONY : Code/StateMachine.cpp.o

Code/StateMachine.i: Code/StateMachine.cpp.i

.PHONY : Code/StateMachine.i

# target to preprocess a source file
Code/StateMachine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/StateMachine.cpp.i
.PHONY : Code/StateMachine.cpp.i

Code/StateMachine.s: Code/StateMachine.cpp.s

.PHONY : Code/StateMachine.s

# target to generate assembly for a file
Code/StateMachine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/StateMachine.cpp.s
.PHONY : Code/StateMachine.cpp.s

Code/ToolsSubject.o: Code/ToolsSubject.cpp.o

.PHONY : Code/ToolsSubject.o

# target to build an object file
Code/ToolsSubject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/ToolsSubject.cpp.o
.PHONY : Code/ToolsSubject.cpp.o

Code/ToolsSubject.i: Code/ToolsSubject.cpp.i

.PHONY : Code/ToolsSubject.i

# target to preprocess a source file
Code/ToolsSubject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/ToolsSubject.cpp.i
.PHONY : Code/ToolsSubject.cpp.i

Code/ToolsSubject.s: Code/ToolsSubject.cpp.s

.PHONY : Code/ToolsSubject.s

# target to generate assembly for a file
Code/ToolsSubject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/ToolsSubject.cpp.s
.PHONY : Code/ToolsSubject.cpp.s

Code/ToolsView.o: Code/ToolsView.cpp.o

.PHONY : Code/ToolsView.o

# target to build an object file
Code/ToolsView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/ToolsView.cpp.o
.PHONY : Code/ToolsView.cpp.o

Code/ToolsView.i: Code/ToolsView.cpp.i

.PHONY : Code/ToolsView.i

# target to preprocess a source file
Code/ToolsView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/ToolsView.cpp.i
.PHONY : Code/ToolsView.cpp.i

Code/ToolsView.s: Code/ToolsView.cpp.s

.PHONY : Code/ToolsView.s

# target to generate assembly for a file
Code/ToolsView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/ToolsView.cpp.s
.PHONY : Code/ToolsView.cpp.s

Code/Vehicles/Car.o: Code/Vehicles/Car.cpp.o

.PHONY : Code/Vehicles/Car.o

# target to build an object file
Code/Vehicles/Car.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/Car.cpp.o
.PHONY : Code/Vehicles/Car.cpp.o

Code/Vehicles/Car.i: Code/Vehicles/Car.cpp.i

.PHONY : Code/Vehicles/Car.i

# target to preprocess a source file
Code/Vehicles/Car.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/Car.cpp.i
.PHONY : Code/Vehicles/Car.cpp.i

Code/Vehicles/Car.s: Code/Vehicles/Car.cpp.s

.PHONY : Code/Vehicles/Car.s

# target to generate assembly for a file
Code/Vehicles/Car.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/Car.cpp.s
.PHONY : Code/Vehicles/Car.cpp.s

Code/Vehicles/Truck.o: Code/Vehicles/Truck.cpp.o

.PHONY : Code/Vehicles/Truck.o

# target to build an object file
Code/Vehicles/Truck.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/Truck.cpp.o
.PHONY : Code/Vehicles/Truck.cpp.o

Code/Vehicles/Truck.i: Code/Vehicles/Truck.cpp.i

.PHONY : Code/Vehicles/Truck.i

# target to preprocess a source file
Code/Vehicles/Truck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/Truck.cpp.i
.PHONY : Code/Vehicles/Truck.cpp.i

Code/Vehicles/Truck.s: Code/Vehicles/Truck.cpp.s

.PHONY : Code/Vehicles/Truck.s

# target to generate assembly for a file
Code/Vehicles/Truck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/Truck.cpp.s
.PHONY : Code/Vehicles/Truck.cpp.s

Code/Vehicles/Vehicle.o: Code/Vehicles/Vehicle.cpp.o

.PHONY : Code/Vehicles/Vehicle.o

# target to build an object file
Code/Vehicles/Vehicle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/Vehicle.cpp.o
.PHONY : Code/Vehicles/Vehicle.cpp.o

Code/Vehicles/Vehicle.i: Code/Vehicles/Vehicle.cpp.i

.PHONY : Code/Vehicles/Vehicle.i

# target to preprocess a source file
Code/Vehicles/Vehicle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/Vehicle.cpp.i
.PHONY : Code/Vehicles/Vehicle.cpp.i

Code/Vehicles/Vehicle.s: Code/Vehicles/Vehicle.cpp.s

.PHONY : Code/Vehicles/Vehicle.s

# target to generate assembly for a file
Code/Vehicles/Vehicle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/Vehicle.cpp.s
.PHONY : Code/Vehicles/Vehicle.cpp.s

Code/Vehicles/VehicleFactory.o: Code/Vehicles/VehicleFactory.cpp.o

.PHONY : Code/Vehicles/VehicleFactory.o

# target to build an object file
Code/Vehicles/VehicleFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/VehicleFactory.cpp.o
.PHONY : Code/Vehicles/VehicleFactory.cpp.o

Code/Vehicles/VehicleFactory.i: Code/Vehicles/VehicleFactory.cpp.i

.PHONY : Code/Vehicles/VehicleFactory.i

# target to preprocess a source file
Code/Vehicles/VehicleFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/VehicleFactory.cpp.i
.PHONY : Code/Vehicles/VehicleFactory.cpp.i

Code/Vehicles/VehicleFactory.s: Code/Vehicles/VehicleFactory.cpp.s

.PHONY : Code/Vehicles/VehicleFactory.s

# target to generate assembly for a file
Code/Vehicles/VehicleFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CityTrafficSimulator.dir/build.make CMakeFiles/CityTrafficSimulator.dir/Code/Vehicles/VehicleFactory.cpp.s
.PHONY : Code/Vehicles/VehicleFactory.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CityTrafficSimulator"
	@echo "... Code/AssetManager.o"
	@echo "... Code/AssetManager.i"
	@echo "... Code/AssetManager.s"
	@echo "... Code/Button.o"
	@echo "... Code/Button.i"
	@echo "... Code/Button.s"
	@echo "... Code/CamerasSubject.o"
	@echo "... Code/CamerasSubject.i"
	@echo "... Code/CamerasSubject.s"
	@echo "... Code/CamerasView.o"
	@echo "... Code/CamerasView.i"
	@echo "... Code/CamerasView.s"
	@echo "... Code/Cell.o"
	@echo "... Code/Cell.i"
	@echo "... Code/Cell.s"
	@echo "... Code/CreatorHandler.o"
	@echo "... Code/CreatorHandler.i"
	@echo "... Code/CreatorHandler.s"
	@echo "... Code/CreatorState.o"
	@echo "... Code/CreatorState.i"
	@echo "... Code/CreatorState.s"
	@echo "... Code/CreatorSubject.o"
	@echo "... Code/CreatorSubject.i"
	@echo "... Code/CreatorSubject.s"
	@echo "... Code/FileFinder.o"
	@echo "... Code/FileFinder.i"
	@echo "... Code/FileFinder.s"
	@echo "... Code/Grid.o"
	@echo "... Code/Grid.i"
	@echo "... Code/Grid.s"
	@echo "... Code/InitCreateState.o"
	@echo "... Code/InitCreateState.i"
	@echo "... Code/InitCreateState.s"
	@echo "... Code/InputManager.o"
	@echo "... Code/InputManager.i"
	@echo "... Code/InputManager.s"
	@echo "... Code/LoadDemo.o"
	@echo "... Code/LoadDemo.i"
	@echo "... Code/LoadDemo.s"
	@echo "... Code/LoadState.o"
	@echo "... Code/LoadState.i"
	@echo "... Code/LoadState.s"
	@echo "... Code/Main.o"
	@echo "... Code/Main.i"
	@echo "... Code/Main.s"
	@echo "... Code/MainMenuState.o"
	@echo "... Code/MainMenuState.i"
	@echo "... Code/MainMenuState.s"
	@echo "... Code/MapView.o"
	@echo "... Code/MapView.i"
	@echo "... Code/MapView.s"
	@echo "... Code/SaveState.o"
	@echo "... Code/SaveState.i"
	@echo "... Code/SaveState.s"
	@echo "... Code/SimulationHandler.o"
	@echo "... Code/SimulationHandler.i"
	@echo "... Code/SimulationHandler.s"
	@echo "... Code/SimulationSubject.o"
	@echo "... Code/SimulationSubject.i"
	@echo "... Code/SimulationSubject.s"
	@echo "... Code/Simulator.o"
	@echo "... Code/Simulator.i"
	@echo "... Code/Simulator.s"
	@echo "... Code/SplashState.o"
	@echo "... Code/SplashState.i"
	@echo "... Code/SplashState.s"
	@echo "... Code/StateMachine.o"
	@echo "... Code/StateMachine.i"
	@echo "... Code/StateMachine.s"
	@echo "... Code/ToolsSubject.o"
	@echo "... Code/ToolsSubject.i"
	@echo "... Code/ToolsSubject.s"
	@echo "... Code/ToolsView.o"
	@echo "... Code/ToolsView.i"
	@echo "... Code/ToolsView.s"
	@echo "... Code/Vehicles/Car.o"
	@echo "... Code/Vehicles/Car.i"
	@echo "... Code/Vehicles/Car.s"
	@echo "... Code/Vehicles/Truck.o"
	@echo "... Code/Vehicles/Truck.i"
	@echo "... Code/Vehicles/Truck.s"
	@echo "... Code/Vehicles/Vehicle.o"
	@echo "... Code/Vehicles/Vehicle.i"
	@echo "... Code/Vehicles/Vehicle.s"
	@echo "... Code/Vehicles/VehicleFactory.o"
	@echo "... Code/Vehicles/VehicleFactory.i"
	@echo "... Code/Vehicles/VehicleFactory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

